### ISSUE TITLE
Broken Link to "more about layouts in devon4ng"

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#10]
Category: enhancement

Severity: Low 

Description of issue / expected enhacement /Comments
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application there is a link box with the text 

> Learn more about layouts in devon4ng HERE

The Link is broken.
It is https://github.com/devonfw/devonfw-tutorial-sources/wiki/angular-components#teradata-layouts
It must be https://github.com/devonfw/devonfw-tutorial-sources/wiki/angular-components#teradata-covalent-layouts 

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG , the issue has been solved by changing the link to:

> https://github.com/devonfw/devonfw-tutorial-sources/wiki/angular-components#teradata-covalent-layouts

i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
