### ISSUE TITLE
Routing set up instructions outdated / inconsistent

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#12]
Category: enhancement

Severity: Medium

Description of issue / expected enhacement /Comments
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application it is said:
> Create a file called app-routing.module.ts and add the following code:

The file has already been created by the system when creating the new project with `ng new angular` and option "Would you like to add Angular routing? Yes". 
Note: the file may not have been created if the project was created with devcon (I didn't try). In that case "Create a file [...]" _may_ be valid.

The section ...
> Time to add this AppRoutingModule routing module to the app module in app.module.ts:

... including the code snippets from app.module.ts appear to be obsolete because the changes have already been made by the "Would you like to add Angular routing? Yes" option.

Your environment - windows/Linux, Devonfw version , component
windows

**Comment by trivesc** [comment]
hello @Jan-PeterRichterCG,
An extra note has been added to solve this issue:

> If Angular CLI was used to generate the project and yes was chosen in the option to create Angular routing, this file (app-routing.module.ts) is created automaticly and only modification is needed.

i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
