### ISSUE TITLE
LoginModule and FormLoginModule break the app

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#13]
Category: Bug

Severity: High

Expected behaviour (In case of bug)
after executing the step ...

> Once this is done, we need to remove the FormLoginComponent and then add the FormLoginModule both things in the AppModule

... the app shows at least a nav bar

Actual/current behaviour (In case of bug)
after executing the step, the app shows a white screen.

Steps to reproduce (In case of bug)
follow the tutorial to the point where FormLoginComponent is removed from AppModule and FormLoginModule  is added and save the changes.

Description of issue / expected enhacement /Comments
perhaps there is no bug - this depends on how "add" and "remove" is to be interpreted in detail.
My *working* app.module.ts looks like this:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { CoreModule } from './shared/core.module';


import 'hammerjs';

import { LoginComponent } from './form-login/components/login/login.component';
// import { FormLoginModule } from './form-login/form-login-module';
import { FormLoginComponent } from './form-login/form-login.component';

@NgModule({
  declarations: [
    AppComponent,
    FormLoginComponent,
    LoginComponent
  ],
  imports: [
    BrowserModule,
    // FormLoginModule,
    CoreModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```
when I remove the lines 
`import { FormLoginComponent } from './form-login/form-login.component';` and `FormLoginComponent,` and add `FormLoginModule` by un-commenting the comments as shown above, the app breaks. 

Your environment - windows/Linux, Devonfw version , component

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
This issue has been solved by improving the explanation and removing the extra component in the snippet.

Explanation:
> As you can see, the LoginModule is already added to the FormLoginModule. Once this is done, we need to remove the FormLoginComponent and the LoginComponent from the declarations, since they are already declared in their own modules. Then add the FormLoginModule. Those things are done in the AppModule

Snippet:
```
....
import { FormLoginModule } from './form-login/form-login-module';
....
  declarations: [
    AppComponent,
  ]

  imports: [
    BrowserModule,
    FormLoginModule,
    CoreModule,
    AppRoutingModule
  ]
....
```
i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
