### ISSUE TITLE
Misleading CobiGen instructions for Visitor component

### ISSUE THREAD

**Issue by JKrefting** [devonfw/devonfw-tutorial-sources#14]
Category: Bug

Severity: High

In the second to last paragraph on https://github.com/devonfw/devonfw-tutorial-sources/wiki/devon4j-components called "Visitor component structure (Entity without relations)" it is written that "Finally we are going to repeat the same process using Cobigen with our other Visitor component."

This suggests that you should do the same steps as for the AccessCode component, as this was done before. However, generating the "CRUD REST services (CTOs)" and "CRUD UC logic (CTOs)" for the Visitor component is the wrong choice, instead one should use the same CobiGen increments as for the Queue component, which are "CRUD REST services" and "CRUD UC logic", as stated one paragraph before.

**Comment by trivesc** [comment]
Hello JKrefting,
The guide is specifying in the titles two things when creating the components:
1. Entity without relations
2. Entity with relations
This is so done so people can notice that when using cobigen the options are different for entities that have relations or do not.

I will change the text to clarify it further as soon as possible.
Thanks for the feedback

**Comment by JKrefting** [comment]
Now I see the connection, thank you. I think what wasn't clear to me is that the CTO addition facilitates the relations. Maybe it would be clearer if this relation would be highlighted.

**Comment by trivesc** [comment]
Hello JKrefting,
The issue has been solved by adding the specific step the guide wants the people to repeat. The relation is explained later, when the difference between the cto and eto is explained. Please, review the issue.

Regards, Ctrives

**Comment by JKrefting** [comment]
Hi Ctrives,
where can I see the changed version, https://github.com/devonfw/devonfw-tutorial-sources/wiki/devon4j-components appears to be unchanged.
