### ISSUE TITLE
"Add this code" unclear for Register component

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#15]
Category: enhancement

Severity: Medium

Description of issue / expected enhacement /Comments
https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application#creating-components reads:
> Turning back to login.component.html we have to add this code:
```
<form layout="column" class="pad" (ngSubmit)="submitLogin()" #loginForm="ngForm">
...
<button mat-raised-button type="submit" [disabled]="!loginForm.form.valid">Login</button>
...
<button mat-raised-button (click)="onRegisterClick()" color="primary">Register</button>
```
where do I add the code? at the beginning or at the end of the (already existing) code? From the "..." I conclude that the the lines shall be mixed into the existing code, but where (especially the `<form...` line)? 

[Edit] When I read through the existing code, I see that the code _replaces_ some lines of the existing code. This is not clear from the instruction. What is most confusing is that the new `<form...` line now doesn't have the `#accessForm="ngForm"` anymore. Now it is `#loginForm`. Why is this? what is the reason to change it?
Why is the layout changed from `layout-padding` to `layout="column"` and what is the exact result of this change?
...
OK, analyzing the changes in detail reveals:
- `layout="column"` added to the form. Why?
- `class="pad"`added to the form. Why?
- `(ngSubmit)="submitLogin()"` added to the form. Presumably this refers to: 
> First, when we submit the form, the method submitLogin() is going to be called.
- `#accessForm="ngForm"` changed to `#loginForm="ngForm"` in the form. Why?
-  `layout-padding` removed from the form. Why?
- `type="submit"` added to the login button. Again this is obviously related to the submitLogin().
- `[disabled]="!accessForm.form.valid"` changed to `[disabled]="!loginForm.form.valid"` in the login button. This appears to be related to the renaming (why?) of accessForm to loginForm.
- `(click)="onRegisterClick()` added to the register button. This is obviously related to:
>The other event, when the user clicks the button, (click) will send an event to the function onRegisterClick() that should be in the login.component.ts [...]

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
hello @Jan-PeterRichterCG ,
The issue has been fixed by keeping the layout-padding in the code snippet and removing the class and layout, this way confusion is avoided:

```
<form (ngSubmit)="submitLogin()" #loginForm="ngForm" layout-padding>
...
<button mat-raised-button type="submit" [disabled]="!loginForm.form.valid">Login</button>
...
<button mat-raised-button (click)="onRegisterClick()" color="primary">Register</button>
```
About the change from `#accessForm="ngForm"` to `#loginForm="ngForm"` it is only to improve the readability of the code and has been done in all the snippets regarding this form.

```
<form #loginForm="ngForm" layout-padding>
    <div layout="row" flex>
        <mat-form-field flex>
                <input matInput placeholder="Email" ngModel email name="username" required>
        </mat-form-field>
    </div>
    <div layout="row" flex>
        <mat-form-field flex>
            <input matInput placeholder="Password" ngModel name="password" type="password" required>
        </mat-form-field>
    </div>
    <div layout="row" flex>
    </div>
    <div layout="row" flex layout-margin>
        <div layout="column" flex>
            <button mat-raised-button [disabled]="!loginForm.form.valid">Login</button>
        </div>
        <div layout="column" flex>
            <button mat-raised-button color="primary">Register</button>
        </div>
    </div>
</form>
```

```
<form (ngSubmit)="submitLogin()" #loginForm="ngForm" layout-padding>
...
<button mat-raised-button type="submit" [disabled]="!loginForm.form.valid">Login</button>
...
<button mat-raised-button (click)="onRegisterClick()" color="primary">Register</button>

```

```
...
<form (ngSubmit)="submitLogin(loginForm.form.value)" #loginForm="ngForm" layout-padding>
...
```

am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
