### ISSUE TITLE
`import { RegisterComponent }` should explicitly be mentioned

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#16]
Category: enhancement

Severity: Low 

Description of issue / expected enhacement /Comments
In https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application#creating-components it is said:
> We need to inject an instance of Router object and declare it into the name router in order to use it into the code, as we did on onRegisterClick(), using the navigate function and redirecting to the next view, in our case, using the route we are going to define in app.routing.module.ts: [...]
```
const appRoutes: Routes = [
  { path: 'FormLogin', component: FormLoginComponent},               // Redirect if url path is /FormLogin.
  { path: 'Register', component: RegisterComponent},               // Redirect if url path is /Register.
  { path: '**', redirectTo: '/FormLogin', pathMatch: 'full' }  // Redirect if url path do not match with any other route.
];
```

I suggest to add `import { RegisterComponent } from './register/register.component';` to the code snippet.

It may not be neccessary to explicitly instruct on adding this line because Visual Studio Code analyzes the `{ path: 'Register', component: RegisterComponent}, ` code fragment and indicates the missing import.

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
hello @Jan-PeterRichterCG 
This issue has been solved by explicitly adding the import into the snippet:

```
....
import { RegisterComponent } from './register/register.component';
....
const appRoutes: Routes = [
  { path: 'FormLogin', component: FormLoginComponent},               // Redirect if url path is /FormLogin.
  { path: 'Register', component: RegisterComponent},               // Redirect if url path is /Register.
  { path: '**', redirectTo: '/FormLogin', pathMatch: 'full' }  // Redirect if url path do not match with any other route.
];
....
```
i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
