### ISSUE TITLE
devonfw documentation still uses the term OASP in some cases

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#19]
Category: enhancement

Severity: Medium

Expected behaviour (In case of bug)
The term OASP should be used only where the historic context is obvious like in "devonfw is based on OASP, the former Open Application Standard Platform. OASP has now merged into devonfw and is not a separate product any more."
 
Actual/current behaviour (In case of bug)
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/devonfw-intro I read 
> devon4ng: the OASP implementation based on Angular framework.

Steps to reproduce (In case of bug)
look at https://github.com/devonfw/devonfw-tutorial-sources/wiki/devonfw-intro

Description of issue / expected enhacement /Comments
search for *all* ocurrences of "OASP" in the wiki and remove/replace with devonfw if it is not in a historical context

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
This issue has been solved by searching and finding the uses of "OASP", this should be the last one, the rest are regarding historic context.

> devon4ng: the devonfw implementation based on Angular framework.

i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc
