### ISSUE TITLE
"Build your own devon4j application" contains links to non-existent wiki pages

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#22]
Category: Bug

Severity: Medium

Expected behaviour (In case of bug)
Links point to existing resources

Actual/current behaviour (In case of bug)
several links point to a "create new page" form

Steps to reproduce (In case of bug)
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4j-application click on any link in ...
> Learn more about devonfw initialization here

> You can also create new projects:
    manually from command line see how
    from Eclipse see how

Description of issue / expected enhacement /Comments
see Actual/current behaviour and Steps to reproduce

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
This issue has been fixed by pointing to the right links.

Thanks for the feedback and regards,
trivesc
