### ISSUE TITLE
"relation between visitor and daily queue" must be "relation between visitor and access code"

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#23]
Category: Bug

Severity: Low 

Expected behaviour (In case of bug)
Should be 
> In addition, we will have to represent two relationships:
    The one to one relation between visitor and **access code**.

Actual/current behaviour (In case of bug)
> In addition, we will have to represent two relationships:
    The one to one relation between visitor and **daily queue.**

Steps to reproduce (In case of bug)
look at https://github.com/devonfw/devonfw-tutorial-sources/wiki/devon4j-components#create-your-components 

Description of issue / expected enhacement /Comments
The picture https://raw.githubusercontent.com/wiki/devonfw/devonfw-tutorial-sources/images/devon4j/4.Components/visitor-accesscode.png shows that the one to one relation is between visitor and access code. The text line is mistyped

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
The issue has been solved by switching the relation name to access code:

> The one to one relation between visitor and access code.

i am closing this issue since it has been solved,
thanks for the feedback and regards,
trivesc
