### ISSUE TITLE
Note on error for AccessCodeEntity is outdated

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#24]
Category: Enhancement

Severity: Low

Description of issue / expected enhacement /Comments
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/devon4j-components#visitor-component it is said:
> Note: The AccessCodeEntity is throwing an error as it is not created yet. We will solve it in next step.

However, there is no error if you follow the tutorial.
AccessCodeEntity  is not added to the code of VisitorEntity.

This line of the note should be deleted.

Your environment - windows/Linux, Devonfw version , component
irrelevant

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG ,
The issue has been solved by removing that note about the AccessCodeEntity.

i am closing this issue since it has been solved,
thanks for the feedback and regards,
trivesc
