### ISSUE TITLE
Improvements and bugs on OASP4JS Jump The Queue tutorial

### ISSUE THREAD

**Issue by RobertoGM** [devonfw/devonfw-tutorial-sources#4]
Hello,

2 new colleagues in Valencia went through the Jump The Queue tutorial recently and did a great job highlightning points where they found problems or errors.

As there are some of them, I just attach the complete pdf because there you can see the comment and where in the tutorial the problem is:
[BuildOASP4JsApplication · oasp_oasp-tutorial-sources Wiki GitHub.pdf](https://github.com/oasp/oasp-tutorial-sources/files/2261383/BuildOASP4JsApplication.oasp_oasp-tutorial-sources.Wiki.GitHub.pdf)

**Comment by sjimenez77** [comment]
Not relevant anymore
