### ISSUE TITLE
Postman download URL

### ISSUE THREAD

**Issue by dario-rodriguez** [devonfw/devonfw-tutorial-sources#6]
Category: Bug

Severity: Critical

Description of issue:
In the [wiki](https://github.com/devonfw/devonfw-tutorial-sources/wiki/AnDEVON4jApplication) you can find the following line:
```
To show the backend services results we are going to use Postman plugin for Chrome, although you can use any other similar application.
```
It will redirect you to the chrome web store. The problem is that the postman extension is deprecated for years. So please, change the url to the postman main page https://www.getpostman.com/ and force the people to download the correct version of postman.

Anyway, the best way to install postman in windows is using chocolatey.

**Comment by trivesc** [comment]
The version of postman has been updated. The following urls have been changed:
- [AnDEVON4jApplication](https://github.com/devonfw/devonfw-tutorial-sources/wiki/AnDEVON4jApplication)
- [DEVON4jLayers](https://github.com/devonfw/devonfw-tutorial-sources/wiki/DEVON4jLayers)
