### ISSUE TITLE
Adding Styles to angular.json is ambiguous

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-tutorial-sources#9]
Category: enhancement

Severity: Medium, High, Critical

Description of issue / expected enhacement /Comments
On https://github.com/devonfw/devonfw-tutorial-sources/wiki/build-devon4ng-application it is said 

> Now we have to add these styles in angular/CLI config. Go to .angular.json in the root folder, then search the "styles" array and add theme and Covalent platform.css to make it look like this:

There are _two_ "styles" arrays in angular.json. Is it necessary to add the lines to the first, the second or both?
(by the way, the file is called angular.json, not .angular.json )

Your environment - windows/Linux, Devonfw version , component
windows

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG , the issue has been solved by adding clarity to the text:

> Now we have to add these styles in angular/CLI config. Go to angular.json in the root folder, then search both of the "styles" arrays (inside build and test) and add theme and Covalent platform.css to make it look like this:

i am gonna close this issue since it has been solved,

Thanks for the feedback and regards,
trivesc

**Comment by trivesc** [comment]
Hello @Jan-PeterRichterCG,
The issue has been solved by adding clarification to the text:

> Now we have to add these styles in angular/CLI config. Go to angular.json in the root folder, then search both of the "styles" arrays (inside build and test) and add theme and Covalent platform.css to make it look like this:

I am closing this issue.

Thanks for the feedback and regards,
trivesc

**Comment by Jan-PeterRichterCG** [comment]
Hmmmm... the GitHub platform doesn't seem to have a "Like" button. 
Be asured that I "like" your solution!

Thanks!
Jan-Peter
